name: dsform
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    develop:
      watch:
        - path: './schema'
          action: rebuild